name: Build Flatpak Application

on: [push, workflow_dispatch]

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder nodejs npm

    - name: Setup Flatpak
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Platform//23.08
        sudo flatpak install -y flathub org.freedesktop.Sdk//23.08
        sudo flatpak install -y flathub org.freedesktop.Sdk.Extension.node20//23.08
        sudo flatpak install -y flathub org.flatpak.Builder

    - name: Setup flatpak-node-generator
      run: |
        git clone https://github.com/flatpak/flatpak-builder-tools.git
        cd flatpak-builder-tools/node
        python3 -m pip install --user .
        echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH

    - name: Prepare source code
      run: |
        git clone -b feature/trayicon https://github.com/deviitorinc/LibreLinkUpDesktop.git source-repo
        rm -rf source-repo/node_modules

    - name: Generate package sources
      run: |
        cd source-repo
        flatpak-node-generator npm package-lock.json
        mkdir -p ../flathub
        cp generated-sources.json ../flathub/

    - name: Build and package Electron app
      run: |
        cd source-repo
        npm install --legacy-peer-deps --no-audit --no-fund
        npm run build
        
        # Check what was built
        echo "=== Build output ==="
        find . -type f -name "*.AppImage" -o -name "*.deb" -o -name "*.rpm" | head -10
        ls -la release/ || echo "No release directory"
        ls -la dist/ || echo "No dist directory"

    - name: Create Flatpak manifest using electron-base
      run: |
        mkdir -p flathub
        cd flathub
        cat > rocks.poopjournal.librelinkupdesktop.yml << 'EOF'
        app-id: rocks.poopjournal.librelinkupdesktop
        runtime: org.freedesktop.Platform
        runtime-version: '23.08'
        sdk: org.freedesktop.Sdk
        sdk-extensions:
          - org.freedesktop.Sdk.Extension.node20
        command: sh
        finish-args:
          - --share=ipc
          - --share=network
          - --socket=fallback-x11
          - --socket=wayland
          - --device=dri
          - --filesystem=home
          - --filesystem=xdg-run/gvfs

        modules:
          - name: app-bundle
            buildsystem: simple
            build-commands:
              - |
                # Install Node.js dependencies
                export PATH="/usr/lib/sdk/node20/bin:$PATH"
                npm install --legacy-peer-deps --no-audit --no-fund
                
                # Build the app
                npm run build
                
                # The app should be built in release/app/dist/ or similar
                # Copy the entire app structure
                mkdir -p /app/lib/librelinkupdesktop
                if [ -d "release/app/dist" ]; then
                  cp -r release/app/dist/* /app/lib/librelinkupdesktop/
                elif [ -d "dist" ]; then
                  cp -r dist/* /app/lib/librelinkupdesktop/
                else
                  # Fallback: copy the entire built structure
                  cp -r ./* /app/lib/librelinkupdesktop/ || true
                fi
                
                # Create a launcher script that uses system electron
                cat > /app/bin/librelinkupdesktop << 'SCRIPT'
                #!/bin/sh
                # Use electron from node_modules or system
                if [ -f "/app/lib/librelinkupdesktop/node_modules/electron/dist/electron" ]; then
                  exec /app/lib/librelinkupdesktop/node_modules/electron/dist/electron /app/lib/librelinkupdesktop
                else
                  # Try to use system electron or flatpak electron
                  exec electron /app/lib/librelinkupdesktop
                fi
                SCRIPT
                chmod +x /app/bin/librelinkupdesktop
                
                # Install desktop files
                install -Dm644 resources/icon.png /app/share/icons/hicolor/512x512/apps/rocks.poopjournal.librelinkupdesktop.png
                install -Dm644 rocks.poopjournal.librelinkupdesktop.desktop /app/share/applications/rocks.poopjournal.librelinkupdesktop.desktop
                install -Dm644 rocks.poopjournal.librelinkupdesktop.metainfo.xml /app/share/metainfo/rocks.poopjournal.librelinkupdesktop.metainfo.xml
            sources:
              - type: git
                url: https://github.com/deviitorinc/LibreLinkUpDesktop.git
                branch: feature/trayicon
              - generated-sources.json
        EOF

    - name: Build the Flatpak
      run: |
        cd flathub
        flatpak-builder --user --install --force-clean build-dir rocks.poopjournal.librelinkupdesktop.yml

    - name: Create distributable bundle
      run: |
        cd flathub
        flatpak build-bundle ~/.local/share/flatpak/repo LibreLinkUpDesktop.flatpak rocks.poopjournal.librelinkupdesktop

    - name: Upload Flatpak bundle
      uses: actions/upload-artifact@v4
      with:
        name: LibreLinkUpDesktop-Flatpak
        path: flathub/LibreLinkUpDesktop.flatpak
        retention-days: 7