name: Build Flatpak Application

on: [push, workflow_dispatch]

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder nodejs npm

    - name: Setup Flatpak
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Platform//23.08
        sudo flatpak install -y flathub org.freedesktop.Sdk//23.08
        sudo flatpak install -y flathub org.flatpak.Builder

    - name: Build and package Electron app
      run: |
        git clone -b feature/trayicon https://github.com/deviitorinc/LibreLinkUpDesktop.git source-repo
        cd source-repo
        
        # Install and build
        npm install --legacy-peer-deps --no-audit --no-fund
        npm run build
        
        # Create minimal bundle with just the built files
        mkdir -p ../app-bundle
        
        # Copy the essential built files
        if [ -d "release/app/dist" ]; then
          cp -r release/app/dist/* ../app-bundle/
        elif [ -d "dist" ]; then
          cp -r dist/* ../app-bundle/
        fi
        
        # Copy package.json without scripts
        if [ -f "package.json" ]; then
          node -e "
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('package.json'));
          const minimalPkg = {
            name: pkg.name,
            version: pkg.version,
            main: pkg.main,
            dependencies: { electron: pkg.devDependencies?.electron || '^latest' }
          };
          fs.writeFileSync('../app-bundle/package.json', JSON.stringify(minimalPkg, null, 2));
          "
        fi
        
        # Copy resources
        cp -r resources ../app-bundle/ 2>/dev/null || true
        cp *.desktop ../app-bundle/ 2>/dev/null || true
        cp *.metainfo.xml ../app-bundle/ 2>/dev/null || true
        
        cd ../app-bundle
        
        # Install only electron
        npm install electron --no-audit --no-fund
        
        echo "=== Final bundle ==="
        ls -la
        find . -type f | head -20

    - name: Create Flatpak manifest
      run: |
        mkdir -p flathub
        cd flathub
        cat > rocks.poopjournal.librelinkupdesktop.yml << 'EOF'
        app-id: rocks.poopjournal.librelinkupdesktop
        runtime: org.freedesktop.Platform
        runtime-version: '23.08'
        sdk: org.freedesktop.Sdk
        command: librelinkupdesktop
        finish-args:
          - --share=ipc
          - --share=network
          - --socket=fallback-x11
          - --socket=wayland
          - --device=dri
          - --filesystem=home
          - --filesystem=xdg-run/gvfs

        modules:
          - name: librelinkupdesktop
            buildsystem: simple
            build-commands:
              - |
                # Copy application files
                mkdir -p /app/lib/librelinkupdesktop
                cp -r ../app-bundle/* /app/lib/librelinkupdesktop/
                
                # Create launcher
                mkdir -p /app/bin
                cat > /app/bin/librelinkupdesktop << 'SCRIPT'
                #!/bin/sh
                cd /app/lib/librelinkupdesktop
                export NODE_ENV=production
                exec ./node_modules/.bin/electron .
                SCRIPT
                chmod +x /app/bin/librelinkupdesktop
                
                # Desktop integration
                mkdir -p /app/share/applications
                if [ -f "/app/lib/librelinkupdesktop/rocks.poopjournal.librelinkupdesktop.desktop" ]; then
                  install -Dm644 /app/lib/librelinkupdesktop/rocks.poopjournal.librelinkupdesktop.desktop /app/share/applications/
                else
                  cat > /app/share/applications/rocks.poopjournal.librelinkupdesktop.desktop << 'DESKTOP'
                  [Desktop Entry]
                  Type=Application
                  Name=LibreLinkUp Desktop
                  Exec=librelinkupdesktop
                  Icon=rocks.poopjournal.librelinkupdesktop
                  Categories=Utility;
                  Terminal=false
                  DESKTOP
                fi
                
                mkdir -p /app/share/icons/hicolor/512x512/apps/
                if [ -f "/app/lib/librelinkupdesktop/resources/icon.png" ]; then
                  install -Dm644 /app/lib/librelinkupdesktop/resources/icon.png /app/share/icons/hicolor/512x512/apps/rocks.poopjournal.librelinkupdesktop.png
                fi
            sources:
              - type: dir
                path: ../app-bundle
        EOF

    - name: Build the Flatpak
      run: |
        cd flathub
        flatpak-builder --user --install --force-clean build-dir rocks.poopjournal.librelinkupdesktop.yml

    - name: Create distributable bundle
      run: |
        cd flathub
        flatpak build-bundle ~/.local/share/flatpak/repo LibreLinkUpDesktop.flatpak rocks.poopjournal.librelinkupdesktop

    - name: Upload Flatpak bundle
      uses: actions/upload-artifact@v4
      with:
        name: LibreLinkUpDesktop-Flatpak
        path: flathub/LibreLinkUpDesktop.flatpak
        retention-days: 7