name: Generate and Update Flatpak Sources

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  generate-sources:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder nodejs npm python3 python3-pip python3-venv

    - name: Setup Flatpak
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Platform//23.08
        sudo flatpak install -y flathub org.freedesktop.Sdk//23.08
        sudo flatpak install -y flathub org.flatpak.Builder
        sudo flatpak install -y flathub org.electronjs.Electron2.BaseApp//23.08
        sudo flatpak install -y flathub org.freedesktop.Sdk.Extension.node20//23.08

    - name: Clone source repository
      run: |
        git clone -b feature/trayicon https://github.com/deviitorinc/LibreLinkUpDesktop.git source-repo
        cd source-repo
        
        # Install dependencies to generate package-lock.json if needed
        npm install --legacy-peer-deps --no-audit --no-fund
        
        echo "=== Package-lock.json exists ==="
        [ -f package-lock.json ] && echo "package-lock.json found" || echo "package-lock.json not found"

    - name: Install flatpak-node-generator
      run: |
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        export PATH="$HOME/.local/bin:$PATH"
        
        # Clone and install flatpak-builder-tools
        git clone https://github.com/flatpak/flatpak-builder-tools.git
        cd flatpak-builder-tools/node
        pipx install .
        
        echo "=== flatpak-node-generator installed ==="
        which flatpak-node-generator

    - name: Generate sources.json
      run: |
        cd source-repo
        
        echo "=== Current directory contents ==="
        ls -la
        
        echo "=== Generating sources ==="
        export PATH="$HOME/.local/bin:$PATH"
        flatpak-node-generator npm package-lock.json
        
        echo "=== Generated files ==="
        ls -la generated-sources.json || echo "No generated-sources.json created"
        
        # Copy the generated file to the repository root
        cp generated-sources.json ../generated-sources.json

    - name: Verify generated-sources.json
      run: |
        echo "=== Verifying generated-sources.json ==="
        [ -f generated-sources.json ] && echo "generated-sources.json exists" || exit 1
        
        echo "=== File size ==="
        ls -la generated-sources.json
        
        echo "=== First few lines ==="
        head -20 generated-sources.json

    - name: Commit and push generated-sources.json
      run: |
        # Move the generated file to replace any existing one
        mv generated-sources.json generated-sources.json.new
        mv generated-sources.json.new generated-sources.json
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if file exists in repo and if it has changed
        if [ -f generated-sources.json ]; then
          if git diff --quiet generated-sources.json 2>/dev/null || [ ! -f generated-sources.json ]; then
            echo "No changes to generated-sources.json or file doesn't exist in repo"
            # Add the file if it doesn't exist in repo
            git add generated-sources.json
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Add generated-sources.json for Flatpak build"
              git push
            fi
          else
            git add generated-sources.json
            git commit -m "Update generated-sources.json for Flatpak build"
            git push
          fi
        else
          echo "generated-sources.json not found - something went wrong"
          exit 1
        fi

    - name: Upload generated-sources.json as artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-sources-json
        path: generated-sources.json
        retention-days: 7