name: Build Flatpak Application

on: [push, workflow_dispatch]

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder nodejs npm

    - name: Setup Flatpak
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Platform//23.08
        sudo flatpak install -y flathub org.freedesktop.Sdk//23.08
        sudo flatpak install -y flathub org.flatpak.Builder

    - name: Build Electron application
      run: |
        git clone -b feature/trayicon https://github.com/deviitorinc/LibreLinkUpDesktop.git source-repo
        cd source-repo
        
        # Install and build
        npm install --legacy-peer-deps --no-audit --no-fund
        npm run build
        
        # Create the app bundle directory structure
        mkdir -p ../flathub/app-bundle
        
        # Copy the built application files
        if [ -d "main" ]; then
          cp -r main ../flathub/app-bundle/
        fi
        if [ -d "renderer" ]; then
          cp -r renderer ../flathub/app-bundle/
        fi
        if [ -d "resources" ]; then
          cp -r resources ../flathub/app-bundle/
        fi
        
        # Copy desktop files
        cp *.desktop ../flathub/app-bundle/ 2>/dev/null || true
        cp *.metainfo.xml ../flathub/app-bundle/ 2>/dev/null || true
        
        # Create minimal package.json
        cat > ../flathub/app-bundle/package.json << 'PKGJSON'
        {
          "name": "librelinkupdesktop",
          "version": "1.0.0",
          "main": "./main/main.js",
          "dependencies": {
            "electron": "^latest"
          }
        }
        PKGJSON
        
        cd ../flathub/app-bundle
        
        # Install electron
        npm install electron --no-audit --no-fund
        
        echo "=== App bundle contents ==="
        ls -la
        find . -type f -name "*.js" | head -10

    - name: Create Flatpak manifest with proper syntax
      run: |
        cd flathub
        
        # Create the manifest with proper here-document syntax
        cat > rocks.poopjournal.librelinkupdesktop.yml << 'EOF'
        app-id: rocks.poopjournal.librelinkupdesktop
        runtime: org.freedesktop.Platform
        runtime-version: '23.08'
        sdk: org.freedesktop.Sdk
        command: librelinkupdesktop
        finish-args:
          - --share=ipc
          - --share=network
          - --socket=fallback-x11
          - --socket=wayland
          - --device=dri
          - --filesystem=home
          - --filesystem=xdg-run/gvfs

        modules:
          - name: librelinkupdesktop
            buildsystem: simple
            build-commands:
              - mkdir -p /app/lib/librelinkupdesktop
              - cp -r app-bundle/* /app/lib/librelinkupdesktop/
              - mkdir -p /app/bin
              - |
                cat > /app/bin/librelinkupdesktop << 'SCRIPT_EOF'
                #!/bin/sh
                cd /app/lib/librelinkupdesktop
                export NODE_ENV=production
                export ELECTRON_IS_DEV=0
                exec ./node_modules/.bin/electron .
                SCRIPT_EOF
              - chmod +x /app/bin/librelinkupdesktop
              - mkdir -p /app/share/applications
              - |
                cat > /app/share/applications/rocks.poopjournal.librelinkupdesktop.desktop << 'DESKTOP_EOF'
                [Desktop Entry]
                Type=Application
                Name=LibreLinkUp Desktop
                Exec=librelinkupdesktop
                Icon=rocks.poopjournal.librelinkupdesktop
                Comment=LibreLinkUp Desktop Application
                Categories=Utility;
                Terminal=false
                DESKTOP_EOF
              - mkdir -p /app/share/icons/hicolor/512x512/apps/
              - |
                if [ -f "/app/lib/librelinkupdesktop/resources/icon.png" ]; then
                  install -Dm644 /app/lib/librelinkupdesktop/resources/icon.png /app/share/icons/hicolor/512x512/apps/rocks.poopjournal.librelinkupdesktop.png
                fi
              - mkdir -p /app/share/metainfo/
              - |
                if [ -f "/app/lib/librelinkupdesktop/rocks.poopjournal.librelinkupdesktop.metainfo.xml" ]; then
                  install -Dm644 /app/lib/librelinkupdesktop/rocks.poopjournal.librelinkupdesktop.metainfo.xml /app/share/metainfo/rocks.poopjournal.librelinkupdesktop.metainfo.xml
                fi
            sources:
              - type: dir
                path: app-bundle
        EOF

    - name: Verify files exist
      run: |
        cd flathub
        echo "=== Checking app-bundle contents ==="
        ls -la app-bundle/
        echo "=== Checking for main directory ==="
        ls -la app-bundle/main/ 2>/dev/null || echo "No main directory"
        echo "=== Checking for main.js ==="
        find app-bundle -name "main.js" | head -5

    - name: Build the Flatpak
      run: |
        cd flathub
        flatpak-builder --user --install --force-clean build-dir rocks.poopjournal.librelinkupdesktop.yml

    - name: Create distributable bundle
      run: |
        cd flathub
        flatpak build-bundle ~/.local/share/flatpak/repo LibreLinkUpDesktop.flatpak rocks.poopjournal.librelinkupdesktop

    - name: Upload Flatpak bundle
      uses: actions/upload-artifact@v4
      with:
        name: LibreLinkUpDesktop-Flatpak
        path: flathub/LibreLinkUpDesktop.flatpak
        retention-days: 7