name: Build Flatpak

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder

    - name: Setup Flatpak
      run: |
        flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak --user install -y flathub org.flatpak.Builder
        flatpak --user install -y flathub org.electronjs.Electron2.BaseApp//23.08
        flatpak --user install -y flathub org.freedesktop.Sdk.Extension.node20//23.08

    - name: Explore source repository structure
      run: |
        git clone https://github.com/deviitorinc/LibreLinkUpDesktop.git -b feature/trayicon librelinkup-source
        cd librelinkup-source
        echo "=== Repository Contents ==="
        ls -la
        echo "=== Looking for YAML files ==="
        find . -name "*.yml" -o -name "*.yaml" | head -20
        echo "=== Looking for Flatpak configuration files ==="
        find . -name "*.json" -o -name "*.yml" -o -name "*.yaml" | grep -E "(flatpak|manifest)" | head -20

    - name: Build from Flathub repository (if YAML exists elsewhere)
      run: |
        # Clone the Flathub repository that contains the actual YAML file
        git clone https://github.com/flathub/rocks.poopjournal.librelinkupdesktop.git flathub-repo
        cd flathub-repo
        echo "=== Flathub Repository Contents ==="
        ls -la
        echo "=== Looking for YAML files in Flathub repo ==="
        find . -name "*.yml" -o -name "*.yaml" | head -20
        
        # Try to build if YAML file exists
        if [ -f "rocks.poopjournal.librelinkupdesktop.yml" ]; then
          echo "Found YAML file in Flathub repo, building..."
          flatpak-builder --user --install --force-clean build-dir rocks.poopjournal.librelinkupdesktop.yml
        else
          echo "No YAML file found in Flathub repo either"
        fi

    - name: Create bundle from Flathub repo
      run: |
        cd flathub-repo
        if [ -f "rocks.poopjournal.librelinkupdesktop.yml" ]; then
          flatpak-builder --force-clean --repo=repo build-dir rocks.poopjournal.librelinkupdesktop.yml
          flatpak build-bundle repo librelinkupdesktop.flatpak rocks.poopjournal.librelinkupdesktop
          cp librelinkupdesktop.flatpak ..
        else
          echo "Cannot create bundle - no YAML file found"
        fi

    - name: Save artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: repository-exploration
        path: |
          librelinkup-source/
          flathub-repo/
        retention-days: 30