name: Build Flatpak

on: [push, workflow_dispatch]

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder python3-pip

    - name: Setup Flatpak repositories
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.flatpak.Builder
        sudo flatpak install -y flathub org.electronjs.Electron2.BaseApp//23.08
        sudo flatpak install -y flathub org.freedesktop.Sdk.Extension.node20//23.08

    - name: Clone source repository
      run: |
        git clone -b feature/trayicon https://github.com/deviitorinc/LibreLinkUpDesktop.git source-repo

    - name: Install flatpak-node-generator
      run: |
        git clone https://github.com/flatpak/flatpak-builder-tools.git
        cd flatpak-builder-tools/node
        pip3 install .
        echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH

    - name: Generate sources.json
      run: |
        cd source-repo
        rm -rf node_modules
        flatpak-node-generator npm package-lock.json
        # Copy to current directory (where the workflow runs)
        cp generated-sources.json ../

    - name: Verify current directory structure
      run: |
        echo "=== Current Directory Contents ==="
        ls -la
        echo "=== Looking for YAML files ==="
        find . -name "*.yml" -o -name "*.yaml" | head -20

    - name: Build Flatpak application
      run: |
        # The manifest should be in the root directory
        flatpak-builder --user --install --force-clean build-dir rocks.poopjournal.librelinkupdesktop.yml

    - name: Create Flatpak bundle
      run: |
        flatpak build-bundle ~/.local/share/flatpak/repo LibreLinkUpDesktop.flatpak rocks.poopjournal.librelinkupdesktop

    - name: Upload Flatpak bundle as artifact
      uses: actions/upload-artifact@v4
      with:
        name: LibreLinkUpDesktop-Flatpak
        path: LibreLinkUpDesktop.flatpak
        retention-days: 7