name: Build Flatpak

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder python3-pip python3-venv

    - name: Setup Flatpak (user mode)
      run: |
        # Configure Flatpak for user mode instead of system mode
        flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak --user install -y flathub org.flatpak.Builder
        flatpak --user install -y flathub org.electronjs.Electron2.BaseApp//23.08
        flatpak --user install -y flathub org.freedesktop.Sdk.Extension.node20//23.08

    - name: Get source and generate files
      run: |
        git clone https://github.com/deviitorinc/LibreLinkUpDesktop.git -b feature/trayicon source
        cd source
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        export PATH="$HOME/.local/bin:$PATH"
        pipx install flatpak-node-generator
        flatpak-node-generator npm package-lock.json
        cp generated-sources.json ..

    - name: Update sources
      run: |
        cp generated-sources.json .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add generated-sources.json
        git commit -m "Update generated-sources.json" || echo "No changes to commit"
        git push || echo "Nothing to push"

    - name: Build and install (user mode)
      run: |
        flatpak-builder --user --install --force-clean build-dir rocks.poopjournal.librelinkupdesktop.yml

    - name: Create bundle
      run: |
        flatpak-builder --force-clean --repo=repo build-dir rocks.poopjournal.librelinkupdesktop.yml
        flatpak build-bundle repo librelinkupdesktop.flatpak rocks.poopjournal.librelinkupdesktop

    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: librelinkupdesktop-flatpak
        path: librelinkupdesktop.flatpak
        retention-days: 30