name: Build Flatpak Application

on: [push, workflow_dispatch]

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder nodejs npm

    - name: Setup Flatpak
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Platform//23.08
        sudo flatpak install -y flathub org.freedesktop.Sdk//23.08
        sudo flatpak install -y flathub org.flatpak.Builder

    - name: Build Electron app outside Flatpak
      run: |
        git clone -b feature/trayicon https://github.com/deviitorinc/LibreLinkUpDesktop.git source-repo
        cd source-repo
        npm install --legacy-peer-deps --no-audit --no-fund
        npm run build
        
        # Create a simple package structure
        mkdir -p ../app-bundle
        cp -r . ../app-bundle/
        cd ../app-bundle
        
        # Install production dependencies only
        npm install --production --no-audit --no-fund --legacy-peer-deps
        
        echo "=== Final app structure ==="
        find . -name "*.js" -o -name "*.html" -o -name "package.json" | head -20

    - name: Create simple Flatpak manifest
      run: |
        mkdir -p flathub
        cd flathub
        cat > rocks.poopjournal.librelinkupdesktop.yml << 'EOF'
        app-id: rocks.poopjournal.librelinkupdesktop
        runtime: org.freedesktop.Platform
        runtime-version: '23.08'
        sdk: org.freedesktop.Sdk
        command: sh
        finish-args:
          - --share=ipc
          - --share=network
          - --socket=fallback-x11
          - --socket=wayland
          - --device=dri
          - --filesystem=home

        modules:
          - name: librelinkupdesktop
            buildsystem: simple
            build-commands:
              - |
                # Copy the pre-built application
                mkdir -p /app/lib/librelinkupdesktop
                cp -r ../app-bundle/* /app/lib/librelinkupdesktop/
                
                # Install electron in the app directory
                cd /app/lib/librelinkupdesktop
                npm install electron --save --production --no-audit --no-fund
                
                # Create launcher script
                mkdir -p /app/bin
                cat > /app/bin/librelinkupdesktop << 'SCRIPT'
                #!/bin/sh
                cd /app/lib/librelinkupdesktop
                exec ./node_modules/.bin/electron .
                SCRIPT
                chmod +x /app/bin/librelinkupdesktop
                
                # Create basic desktop file
                mkdir -p /app/share/applications
                cat > /app/share/applications/rocks.poopjournal.librelinkupdesktop.desktop << 'DESKTOP'
                [Desktop Entry]
                Name=LibreLinkUp Desktop
                Exec=librelinkupdesktop
                Icon=rocks.poopjournal.librelinkupdesktop
                Type=Application
                Categories=Utility;
                DESKTOP
                
                # Create basic icon
                mkdir -p /app/share/icons/hicolor/512x512/apps/
                if [ -f "resources/icon.png" ]; then
                  cp resources/icon.png /app/share/icons/hicolor/512x512/apps/rocks.poopjournal.librelinkupdesktop.png
                else
                  # Create placeholder icon
                  convert -size 512x512 xc:blue /app/share/icons/hicolor/512x512/apps/rocks.poopjournal.librelinkupdesktop.png 2>/dev/null || \
                  echo "No icon available, using default"
                fi
            sources:
              - type: dir
                path: ../app-bundle
        EOF

    - name: Build the Flatpak
      run: |
        cd flathub
        flatpak-builder --user --install --force-clean build-dir rocks.poopjournal.librelinkupdesktop.yml

    - name: Create distributable bundle
      run: |
        cd flathub
        flatpak build-bundle ~/.local/share/flatpak/repo LibreLinkUpDesktop.flatpak rocks.poopjournal.librelinkupdesktop

    - name: Upload Flatpak bundle
      uses: actions/upload-artifact@v4
      with:
        name: LibreLinkUpDesktop-Flatpak
        path: flathub/LibreLinkUpDesktop.flatpak
        retention-days: 7