name: Build Flatpak

on: [push, workflow_dispatch]

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder python3-pip

    - name: Setup Flatpak repositories (with sudo)
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.flatpak.Builder
        sudo flatpak install -y flathub org.electronjs.Electron2.BaseApp//23.08
        sudo flatpak install -y flathub org.freedesktop.Sdk.Extension.node20//23.08

    - name: Clone source repository
      run: |
        git clone -b feature/trayicon https://github.com/deviitorinc/LibreLinkUpDesktop.git source-repo

    - name: Install flatpak-node-generator
      run: |
        git clone https://github.com/flatpak/flatpak-builder-tools.git
        cd flatpak-builder-tools/node
        pip3 install .
        echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH

    - name: Generate sources.json
      run: |
        cd source-repo
        # Remove existing node_modules if any
        rm -rf node_modules
        # Generate new sources
        flatpak-node-generator npm package-lock.json
        # Copy to flathub directory
        cp generated-sources.json ../flathub/

    - name: Verify files exist in flathub directory
      run: |
        cd flathub
        ls -la
        echo "Checking for manifest file..."
        test -f rocks.poopjournal.librelinkupdesktop.yml && echo "Manifest found" || echo "Manifest missing"
        echo "Checking for generated-sources.json..."
        test -f generated-sources.json && echo "generated-sources.json found" || echo "generated-sources.json missing"

    - name: Build Flatpak application
      run: |
        cd flathub
        flatpak-builder --user --install --force-clean build-dir rocks.poopjournal.librelinkupdesktop.yml

    - name: Create Flatpak bundle
      run: |
        cd flathub
        flatpak build-bundle ~/.local/share/flatpak/repo LibreLinkUpDesktop.flatpak rocks.poopjournal.librelinkupdesktop

    - name: Upload Flatpak bundle as artifact
      uses: actions/upload-artifact@v4
      with:
        name: LibreLinkUpDesktop-Flatpak
        path: flathub/LibreLinkUpDesktop.flatpak
        retention-days: 7

    - name: Test Flatpak installation
      run: |
        cd flathub
        # Test installing from the bundle
        flatpak install -y --user LibreLinkUpDesktop.flatpak
        # Verify it was installed
        flatpak list | grep rocks.poopjournal.librelinkupdesktop && echo "Installation successful" || echo "Installation failed"